import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MusicPlayer from "@/components/templates/musicPlayer/MusicPlayer";
import ASideBar from "@/components/templates/AsideBar/ASideBar";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/modules/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ScrollerEffects`}>
        <StoreProvider>
          <Navbar/>
          <main className="flex h-[85vh] ">
            <div className=" p-3 max-md:p-0 rounded-lg overflow-hidden">

            <ASideBar />
            </div>
            <section className="bg-[#0f0f0f] h-[85vh] ScrollerEffects  w-full overflow-auto p-3">
              {children}
            </section>
            <MusicPlayer />
          </main>
        </StoreProvider>
        
      </body>
    </html>
  );
}
