import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MusicPlayer from "@/components/musicPlayer/MusicPlayer";
import ASideBar from "@/components/AsideBar/ASideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <main className="flex min-h-screen">
             <ASideBar/>
          <section className="bg-[#0f0f0f] w-full overflow-auto">{children}
          </section>
          
          <MusicPlayer />
        </main>
      </body>
    </html>
  );
}
